import = [
  '~/.config/alacritty/themes/everforest_dark.toml'
]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "0x1a1a1a"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true


# [colors.primary]
# background = "0x181b22"
# foreground = "0xd8dee9"
#
[colors.cursor]
text = "CellBackground"
cursor = "0xB8DABB"
#
# [colors.vi_mode_cursor]
# text = "0x2e3440"
# cursor = "0xd8dee9"
#
# [colors.selection]
# text = "0xd8dee9" # Note: TOML does not support referencing like YAML, so "CellForeground" will need to be manually replaced or interpreted by the application.
# background = "0x4c566a"

[mouse]
hide_when_typing = true

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "alacritty"

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.offset]
y = 2

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "Buttonless"
blur=true
opacity=0.9
