live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "0x1a1a1a"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x6e6a86"
blue = "0x9ccfd8"
cyan = "0xebbcba"
green = "0x31748f"
magenta = "0xc4a7e7"
red = "0xeb6f92"
white = "0xe0def4"
yellow = "0xf6c177"

[colors.cursor]
cursor = "0xF5F5DC"
text = "0x1a1a1a"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "0x26233a"
blue = "0x9ccfd8"
cyan = "0xebbcba"
green = "0x31748f"
magenta = "0xc4a7e7"
red = "0xeb6f92"
white = "0xe0def4"
yellow = "0xf6c177"

[colors.primary]
background = "0x191724"
foreground = "0xe0def4"

[colors.selection]
background = "0x403d52"
text = "0xe0def4"

[colors.vi_mode_cursor]
cursor = "0x524f67"
text = "0xe0def4"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "alacritty"

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[font.offset]
y = 2

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "Buttonless"
