import = [
  '~/.config/alacritty/themes/everforest_dark.toml'
]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "0x1a1a1a"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

# [colors.primary]
# background = "0x181b22"
# foreground = "0xd8dee9"
#
# [colors.cursor]
# text = "0x2e3440"
# cursor = "0xd8dee9"
#
# [colors.vi_mode_cursor]
# text = "0x2e3440"
# cursor = "0xd8dee9"
#
# [colors.selection]
# text = "0xd8dee9" # Note: TOML does not support referencing like YAML, so "CellForeground" will need to be manually replaced or interpreted by the application.
# background = "0x4c566a"
#
# [colors.normal]
# black = "0x3b4252"
# red = "0xbf616a"
# green = "0xa3be8c"
# yellow = "0xebcb8b"
# blue = "0x81a1c1"
# magenta = "0xb48ead"
# cyan = "0x88c0d0"
# white = "0xe5e9f0"
#
# [colors.bright]
# black = "0x4c566a"
# red = "0xbf616a"
# green = "0xa3be8c"
# yellow = "0xebcb8b"
# blue = "0x81a1c1"
# magenta = "0xb48ead"
# cyan = "0x8fbcbb"
# white = "0xeceff4"
#
# [colors.dim]
# black = "0x373e4d"
# red = "0x94545d"
# green = "0x809575"
# yellow = "0xb29e75"
# blue = "0x68809a"
# magenta = "0x8c738c"
# cyan = "0x6d96a5"
# white = "0xaeb3bb"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "alacritty"

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[font.offset]
y = 2

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "Buttonless"
