format = """
$all\
$fill\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$line_break\
$character\
"""

[nodejs]
format = "[$symbol($version )]($style)"

[fill]
symbol = " "

[directory]
style = "#c6a0f6 bold"
read_only = " "
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = "[❯](#a6da95)"
error_symbol = "[❯](#eb6f92)"
vicmd_symbol = "[❮](#a6da95)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-yellow bold"

[jobs]
symbol = ""
style = "bold #ed8796"
number_threshold = 1
format = "[$symbol]($style)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "#91d7e3"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "#eed49f"

[memory_usage]
symbol = " "

# [time]
# disabled = false
# style = "bold white"
# format = "[$time]($style)"

